"""add email and password to users

Revision ID: 90a2eceb6943
Revises: 7632576b1b66
Create Date: 2017-03-14 21:56:47.225912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90a2eceb6943'
down_revision = '7632576b1b66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column(
        'email', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('password_hash',
                                     sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
